# Generated by Django 5.1 on 2024-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartouches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='code_demandeur',
            field=models.CharField(default='CODE123', max_length=50),
        ),
        migrations.AddField(
            model_name='demande',
            name='nom_demandeur',
            field=models.CharField(default='Nom inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartouchemodel',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
