# Generated by Django 5.1 on 2024-09-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartouches', '0002_demande_code_demandeur_demande_nom_demandeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='code_demandeur',
            field=models.CharField(default='123...', max_length=50),
        ),
    ]
